# Generated by Django 3.1.4 on 2021-01-12 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='orgname', max_length=20, verbose_name='조직 이름')),
                ('desc', models.TextField(default='', verbose_name='조직 소개')),
                ('members', models.ManyToManyField(through='portal.Membership', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.organization'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
