# Python to Linux Web App on Azure

# Build your Python project and deploy it to Azure as a Linux Web App.
# Change python version to one thats appropriate for your application.
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main
- develop

variables:
  # Agent VM image name
  vmImageName: 'ubuntu-20.04'
  # Python version: 3.8
  platformName: python
  platformVersion: '3.8'
  runtimePlatform: 'PYTHON|3.8'
  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)
  azSubscription: 'Azure_Deploy_to_MPN-Production-스폰서쉽-Gold'
  azWebAppName: 'mate365billing'
  # Environment name
  ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    environmentName: 'BillingPortal-Production'
  ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
    environmentName: 'BillingPortal-Staging'

resources:
  containers:
  - container: oryx
    image: mcr.microsoft.com/oryx/build:latest

stages:
- stage: BuildAndDeploy
  displayName: Build and Deploy stage
  jobs:
  - job: BuildAndDeployJob
    pool:
      vmImage: $(vmImageName)
    # container: mcr.microsoft.com/oryx/build:latest
    steps:

    - script: |
        oryx build
      env:
        POST_BUILD_COMMAND: python manage.py collectstatic
      displayName: Build App using Oryx
      target: oryx
    - task: AzureAppServiceSettings@1
      displayName: Update Settings for $(environmentName) App Service
      inputs:
        azureSubscription: $(azSubscription)
        appName: $(azWebAppName)
        appSettings: |
          [
            {
              "name": "WEBSITE_RUN_FROM_PACKAGE",
              "value": "1",
              "slotSetting": false
            }
          ]
    - task: AzureRmWebAppDeployment@4
      displayName: 'Deploy to Web App $(environmentName)'
      condition: eq(variables['Build.SourceBranchName'], 'main')
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: $(azSubscription)
        appType: 'webAppLinux'
        WebAppName: $(azWebAppName)
        package: '$(projectRoot)'
        RuntimeStack: $(runtimePlatform)
        deploymentMethod: 'runFromPackage'
        
    - task: AzureRmWebAppDeployment@4
      displayName: 'Deploy to Web App $(environmentName)'
      condition: eq(variables['Build.SourceBranchName'], 'develop')
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: $(azSubscription)
        appType: 'webAppLinux'
        WebAppName: $(azWebAppName)
        package: '$(projectRoot)'
        RuntimeStack: $(runtimePlatform)
        deploymentMethod: 'runFromPackage'
        slotName: staging
          
              