


# Python to Linux Web App on Azure

# Build your Python project and deploy it to Azure as a Linux Web App.
# Change python version to one thats appropriate for your application.
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main
- develop

variables:
  dockerRegistryServiceConnection: '5dbad1df-cde9-49af-bced-1351d0c9539a'
  containerRegistry: 'matebilling.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  # Agent VM image name
  vmImageName: 'ubuntu-20.04'
  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)
  azSubscription: 'Azure_Deploy_to_MPN-Production-스폰서쉽-Gold'
  azWebAppName: 'matebilling'
  # Environment name
  ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    environmentName: 'BillingPortal-Production'
    imageRepository: 'prod'
  ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
    environmentName: 'BillingPortal-Staging'
    imageRepository: 'dev'

stages:
- stage: BuildAndDeploy
  displayName: Build and Deploy stage
  jobs:
  - job: BuildAndDeployJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: $(tag)

    - task: AzureWebAppContainer@1 # Add this at the end of your file
      displayName: 'Deploy to Web App $(environmentName)'
      condition: eq(variables['Build.SourceBranchName'], 'develop')
      inputs:
        azureSubscription: $(azSubscription)
        appName: $(azWebAppName)
        containers: $(containerRegistry)/$(imageRepository):$(tag)
        slotName: staging
    
    - task: AzureWebAppContainer@1 # Add this at the end of your file
      displayName: 'Deploy to Web App $(environmentName)'
      condition: eq(variables['Build.SourceBranchName'], 'main')
      inputs:
        azureSubscription: $(azSubscription)
        appName: $(azWebAppName)
        containers: $(containerRegistry)/$(imageRepository):$(tag)


              