# Generated by Django 3.1.4 on 2021-01-21 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organizationinvitation'),
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='org_last_selected',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='organizations.organization'),
        ),
    ]
