# Generated by Django 3.1.4 on 2021-01-21 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organizationinvitation'),
        ('custom', '0002_mcuser_org_last_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='organizations.organization')),
                ('company_registration_number', models.CharField(blank=True, max_length=16, verbose_name='사업자번호')),
                ('location', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='custom.user')),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('location', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('organizations.organization',),
        ),
        migrations.CreateModel(
            name='OrgUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('organizations.organizationuser',),
        ),
    ]
