# Generated by Django 3.1.4 on 2021-01-27 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organizationinvitation'),
        ('custom', '0004_auto_20210121_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationVendor',
            fields=[
                ('seq', models.AutoField(db_column='Seq', primary_key=True, serialize=False)),
                ('vendorcode', models.IntegerField(db_column='VendorCode')),
                ('vendorkey', models.CharField(db_column='VendorKey', max_length=200)),
                ('regdate', models.DateTimeField(db_column='RegDate')),
                ('orgid', models.ForeignKey(db_column='OrgId', on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.organization')),
            ],
            options={
                'db_table': 'Organization_Vendor',
                'managed': False,
            },
        ),
    ]
