# Generated by Django 3.1.5 on 2021-02-04 06:16
# joseph.kim 수정

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0005_organizationvendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='info',
            field=models.CharField(blank=True, default=None, max_length=16, null=True, verbose_name='동의한 이용약관'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='info_protection',
            field=models.CharField(blank=True, default=None, max_length=16, null=True, verbose_name='동의한 개인정보보호'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='info_protection_updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='개인정보보호 동의 시간'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='info_updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='이용약관 동의 시간'),
        ),
    ]
