# Generated by Django 3.1.4 on 2021-03-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0006_auto_20210204_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationvendor',
            options={'managed': False, 'verbose_name': '조직별 클라우드 연결', 'verbose_name_plural': '조직별 클라우드 연결'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
